services:
  proxy:
    image: proxy
    build:
      context: ./nginx
    ports:
      - "80:80"
  frontend:
    image: frontend
    build:
      context: ./client
  backend:
    image: backend
    build:
      context: ./server
  mongodb:
    image: mongo:7.0.5
  scripts:
    image: scripts
    build:
      context: ./bash